name: LoupGarouUHC
version: 1.0.0
author: Dams333
main: ch.dams333.lgUhc.LgUhc
api-version: 1.13
commands:
  lg:
    permission: lg.commands.lg
    description: Commande du plugin loup garou
  lgreload:
    permission: lg.commands.lgreload
    description: recharge votre joueur